"""crear tabla productos

Revision ID: 70571a2901a7
Revises: 71dbe5c17f02
Create Date: 2026-03-12 08:31:23.435589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70571a2901a7'
down_revision = '71dbe5c17f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    # ### end Alembic commands ###
